name: C/C++ CI

on:
  push:
    branches: [ imgui ]
  pull_request:
    branches: [ imgui ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
    - run: make
